services:
  backend:
    build:
      context: .
      dockerfile: ops/docker/Dockerfile.backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - WALLBOX_HOST=${WALLBOX_HOST}
    networks:
      - hiko-network

  frontend:
    build:
      context: .
      dockerfile: ops/docker/Dockerfile.frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - hiko-network

networks:
  hiko-network:
    driver: bridge
