services:
  backend:
    build:
      context: .
      dockerfile: ops/docker/Dockerfile.backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - WALLBOX_HOST=${WALLBOX_HOST}
