openapi: 3.1.1
info:
  title: Hiko Backend API
  description: The API of the backend the frontend connects to.
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api'
paths:
  /wallbox/state:
    get:
      summary: Get the state of the wallbox
      operationId: getWallboxState
      responses:
        '200':
          description: The state of the wallbox
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WallboxState'
components:
  schemas:
    WallboxState:
      type: object
      required:
        - connectionState
        - power
        - charged
        - duration
      properties:
        connectionState:
          type: string
          enum:
            - NoVehicleConnected
            - ConnectedNotCharging
            - ConnectedCharging
        power:
          $ref: '#/components/schemas/Measurement'
        charged:
          $ref: '#/components/schemas/Measurement'
        duration:
          $ref: '#/components/schemas/Measurement'
    Measurement:
      type: object
      required:
        - value
        - unit
      properties:
        value:
          type: number
        unit:
          type: string
